Repository BanklessDAO/mad-hatter, pull requests merged in 2021-11, with the labels that each got.

#6 PR prep
  .github/workflows/build-test.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-qa.yml
  CHANGELOG.md
  src/app/commands/coordinape/Coordinape.ts
  src/app/commands/timecard/Timecard.ts
  src/app/events/MessageCreate.ts
  src/app/events/chat/MessageCreateOnDEGEN.ts
  src/app/service/constants/constants.ts
  src/app/service/constants/degenPhrases.ts
  src/app/service/first-quest/FirstQuestPOAP.ts
  src/app/types/poap/POAPAdmin.ts
  src/app/types/poap/POAPParticipant.ts
  src/app/types/poap/POAPSettings.ts
  src/app/types/poap/POAPTwitterParticipants.ts
  src/app/types/poap/POAPTwitterSettings.ts
  src/app/types/poap/POAPUnclaimedParticipants.ts
  src/app/utils/POAPUtils.ts
Labels: enhancement

#15 Hotfix/1.0.1
  .env.prod
  CHANGELOG.md
  docs/BOT_PERMISSIONS.md
  package.json
  src/app/commands/scoap-squad/ScoapSquad.ts
  src/app/events/GuildMemberAdd.ts
  src/app/events/MessageCreate.ts
  src/app/events/Ready.ts
  src/app/events/chat/HandleAFK.ts
  src/app/events/chat/MessageCreateOnDEGEN.ts
  src/app/service/constants/degenPhrases.ts
  src/app/service/first-quest/ConfigureFirstQuest.ts
  src/app/service/first-quest/FirstQuestPOAP.ts
  src/app/service/first-quest/LaunchFirstQuest.ts
Labels: enhancement

#18 Feature/first quest enhancments
  .env.prod
  .env.qa
  CHANGELOG.md
  package.json
  src/app/commands/afk/AFK.ts
  src/app/commands/bounty/Bounty.ts
  src/app/commands/coordinape/Coordinape.ts
  src/app/commands/first-quest/FirstQuest.ts
  src/app/commands/fun/roll.ts
  src/app/commands/notion/NotionFAQs.ts
  src/app/commands/scoap-squad/ScoapSquad.ts
  src/app/commands/timecard/Timecard.ts
  src/app/events/GuildMemberAdd.ts
  src/app/events/GuildMemberUpdate.ts
  src/app/events/MessageCreate.ts
  src/app/events/Ready.ts
  src/app/events/first-quest/StartFirstQuestFlow.ts
  src/app/events/first-quest/messageLaunchFirstQuest.ts
  src/app/service/constants/channelIds.ts
  src/app/service/constants/firstQuest.ts
  src/app/service/first-quest/ConfigureFirstQuest.ts
  src/app/service/first-quest/FirstQuestPOAP.ts
  src/app/service/first-quest/LaunchFirstQuest.ts
  src/app/utils/FirstQuestUtils.ts
  src/app/utils/Log.ts
  src/app/utils/ServiceUtils.ts
Labels: bug, enhancement

#19 Develop
  .env.prod
  .env.qa
  CHANGELOG.md
  package.json
  src/app/commands/afk/AFK.ts
  src/app/commands/bounty/Bounty.ts
  src/app/commands/coordinape/Coordinape.ts
  src/app/commands/first-quest/FirstQuest.ts
  src/app/commands/fun/roll.ts
  src/app/commands/notion/NotionFAQs.ts
  src/app/commands/scoap-squad/ScoapSquad.ts
  src/app/commands/timecard/Timecard.ts
  src/app/events/GuildMemberAdd.ts
  src/app/events/GuildMemberUpdate.ts
  src/app/events/MessageCreate.ts
  src/app/events/Ready.ts
  src/app/events/first-quest/StartFirstQuestFlow.ts
  src/app/events/first-quest/messageLaunchFirstQuest.ts
  src/app/service/constants/channelIds.ts
  src/app/service/constants/firstQuest.ts
  src/app/service/first-quest/ConfigureFirstQuest.ts
  src/app/service/first-quest/FirstQuestPOAP.ts
  src/app/service/first-quest/LaunchFirstQuest.ts
  src/app/utils/FirstQuestUtils.ts
  src/app/utils/Log.ts
  src/app/utils/ServiceUtils.ts
Labels: bug, enhancement

#20 Fix/first quest message flow
  CHANGELOG.md
  LICENSE.md
  src/app/commands/first-quest/FirstQuest.ts
  src/app/service/constants/firstQuest.ts
  src/app/service/first-quest/LaunchFirstQuest.ts
Labels: bug

#22 Feature/afk stability
  CHANGELOG.md
  package.json
  src/app/commands/afk/AFK.ts
  src/app/commands/first-quest/FirstQuest.ts
  src/app/events/MessageCreate.ts
  src/app/events/chat/HandleAFK.ts
  src/app/service/AFK/ToggleAFK.ts
Labels: bug

#23 Feature/coordinape forms round
  CHANGELOG.md
  src/app/commands/coordinape/Coordinape.ts
  src/app/service/constants/roleIds.ts
  src/app/service/coordinape/CoordinapeSendForm.ts
  src/app/utils/ServiceUtils.ts
Labels: enhancement

#24 Develop
  CHANGELOG.md
  package.json
  src/app/commands/afk/AFK.ts
  src/app/commands/coordinape/Coordinape.ts
  src/app/commands/first-quest/FirstQuest.ts
  src/app/events/MessageCreate.ts
  src/app/events/chat/HandleAFK.ts
  src/app/service/AFK/ToggleAFK.ts
  src/app/service/constants/roleIds.ts
  src/app/service/coordinape/CoordinapeSendForm.ts
  src/app/utils/ServiceUtils.ts
Labels: enhancement
